### ISSUE TITLE
Can you add something in the comments on how to get the Issuer and Subject? 

### ISSUE THREAD

**Issue by SBPDevelopment** [asjimene/RightClickCodeSign#1]
Thank you so much for writing this!  This is going to be used a lot!  It just took a long time to figured out what my Cert info was.  I used the below to spell it out for me, and then I just used that new info in the switches.  Apologies if you already had this in there.

Get-ChildItem 'Cert:\CurrentUser\My' -CodeSigningCert | format-list

This provides the actual proper info. 

See you in the next AZSMUG.  Steve

**Comment by asjimene** [comment]
You can actually use the-InstallSelectCert to bring up a list of your codesigning certs and select one instead of providing them :)

RightClickToCodeSign.ps1 -Install -InstallSelectCert -timestamp "http://timestamp.digicert.com" -Algorithm SHA256
